production:
  aws_access_key_id: AKIAIMPWJXZ4VS5WYIFQ
  aws_secret_access_key: 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
  fog_directory: sapsb-dev
development:
  aws_access_key_id: AKIAIMPWJXZ4VS5WYIFQ
  aws_secret_access_key: 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
  fog_directory: sapsb-dev

  